GET http://localhost:10010/ping

###
POST http://localhost:10010/ping
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU0NDkxNTMzM30.uLjHPvAll6VNX87heECRA-S26dKzhcembS9bD8rcicM

{
  "message": "asdf",
  "key": 10
}

###
POST http://localhost:10010/account/login
Content-Type: application/json

{
  "password": "1234",
  "login": "test@mail.com",
  "role": "admin"
}

###
PUT http://localhost:10010/account/2
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU1MTM4NTgyN30.EhtOnganVNpFQVY9k7Vd7tE9H1_za-Y22q7VjnVq4ko
Content-Type: application/json

{
  "fname": "Allah",
  "lname": "Ackbar",
  "email": "wow@mail.com"
}


###
GET http://localhost:10010/instrument/asdf
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU0NTU3MDk3M30.kZu3UymIWV9yU6jJEN4uaZ717w66EdHSwEFCKmqfnDU

###
GET http://localhost:10010/instrument/brands
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU0NTU3MDk3M30.kZu3UymIWV9yU6jJEN4uaZ717w66EdHSwEFCKmqfnDU

###
POST http://localhost:10010/instrument/brands
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU0NTU3MDk3M30.kZu3UymIWV9yU6jJEN4uaZ717w66EdHSwEFCKmqfnDU
Content-Type: application/json

{
  "name": "Samsung"
}

###
GET http://localhost:10010/instruments?offset=0&available=false

###
GET http://localhost:10010/instruments/15

###
GET http://localhost:10010/instruments

###
POST http://localhost:10010/orders/2
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU1MTUwNTEzMH0.UJ2rMz1mi--VVAbsgoka3sh6o-0SABedwH1BBbc7OtE

{
  "items": [
    { "item_id": 18, "quantity": 3 },
    { "item_id": 17, "quantity": 2 }
  ]
}

###
POST http://localhost:10010/instruments?type=струнные
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU0NTU3MDk3M30.kZu3UymIWV9yU6jJEN4uaZ717w66EdHSwEFCKmqfnDU
Content-Type: application/json

{
  "name": "joopjop",
  "type_id": 10,
  "brand_id": 2,
  "price": 0,
  "count": 0,
  "availability": true
}

###
POST http://localhost:10010/account/check
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU0NTU3MDk3M30.kZu3UymIWV9yU6jJEN4uaZ717w66EdHSwEFCKmqfnDU

###
GET http://localhost:10010/content/posts?post_type=stock&enabled=true

###
PUT http://localhost:10010/content/posts/1
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOjEsImlhdCI6MTU0NTU3MDk3M30.kZu3UymIWV9yU6jJEN4uaZ717w66EdHSwEFCKmqfnDU

{
  "title": "lol title",
  "body": "<p>hmmm what A content!</p>"
}

###
GET http://localhost:10010/content/post_types